### ISSUE TITLE
Rightlist view setting keeps reverting to List.

### ISSUE THREAD

**Issue by Madddcow** [MikeSiLVO/Aeon-Nox-SiLVO#150]
As per the subject, the Rightlist view setting keeps reverting to List view and there's no way to disable List view.

Is there a setting that I've missed or a fix?
Cheers

**Comment by audiosistem** [comment]
> As per the subject, the Rightlist view setting keeps reverting to List view and there's no way to disable List view.
> 
> Is there a setting that I've missed or a fix? Cheers

Returning to version 7.9.9 may solve your problem. Your choice.
