### ISSUE TITLE
MainMenu focus on touch screen

### ISSUE THREAD

**Issue by KingOswiu** [MikeSiLVO/Aeon-Nox-SiLVO#173]
This may be an old problem, but it is new to me!

When using a completely fresh install of Kodi 20 and Silvio, I tried to navigate using a touch screen.  Most things work but the main menu does not.  Swiping left and right does move the menu but doesn't change the focus item.  What should happen is that as the menu moves the focus moves onto the next item.  Cannot identify the reason but do wonder if it is in includes_home.xml

**Comment by nebulous42069** [comment]
I believe its an issue with wraparound main menu. You should be able to go to Skin Settings/Main Menu/Navigation Style and switch it to "Fixed".

**Comment by MikeSiLVO** [comment]
Skin is not designed for touchscreen devices and I believe this is a Kodi bug so not much I can do on my end
