### ISSUE TITLE
Black bar on bottom everywhere?

### ISSUE THREAD

**Issue by thatso** [MikeSiLVO/Aeon-Nox-SiLVO#175]
I'm on the latest Kodi 20.1.0 with your skin v9.0.0 and frankly I'm not sure if this is on purpose or if I'm simply missing a configuration option, but all screens have a large black bar at the bottom:

![1](https://user-images.githubusercontent.com/40745263/231308653-9d1d9fe9-9a7f-48c8-8427-34300928d60e.jpg)
![2](https://user-images.githubusercontent.com/40745263/231308672-e763e464-2d02-4b18-acc7-0358ed5ecd7c.jpg)
![3](https://user-images.githubusercontent.com/40745263/231308691-2efef1d7-2316-4da4-8a09-574151c2e565.jpg)

This happens also on a completely fresh installation, so it is not a historically messed up configuration issue.

**Comment by thatso** [comment]
Thank you for your fast response and explanation, much appreciated! To be honest, I couldn't even remember if it looked that way in previous versions and most of the time it is not even visible. In the weather view however, it looks totally out of place.
I only deleted `floor.png` in your referenced XML file and this already does the trick. Would you suggest deleting the complete control block from lines 68 to 72 instead?

**Comment by MikeSiLVO** [comment]
I'd get rid of 68-72 or the whole group from 57-73.

**Comment by thatso** [comment]
Perfect! Thanks again! :thumbsup:
