### ISSUE TITLE
Australian PG classification icon

### ISSUE THREAD

**Issue by apguy** [MikeSiLVO/Aeon-Nox-SiLVO#177]
In the most recent release 8.10 the PG icon for Australian Classifications has changed colour from yellow background to cyan background.   The correct icon is the yellow background

**Comment by MikeSiLVO** [comment]
I didn't change the color. It looks yellow on the [repo](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/blob/matrix/media/flags/default/mpaa/australia_PG.png)

**Comment by apguy** [comment]
Thanks.   I wonder if there has been something else that has made it change. I did see that you added 

Here are some photos 
![8 10](https://user-images.githubusercontent.com/24578371/232169420-599563a0-109a-4bc3-9af5-eb6355e0808c.JPG)
This is how it is looking in 8.10 (using Kodi 19.4)


![8 01](https://user-images.githubusercontent.com/24578371/232169545-7f401a9b-50b4-4f0a-b859-d3fcd3a3bdbd.JPG)
This is how it always used to look (this was taken in 8.01 also Kodi 19.4)

**Comment by apguy** [comment]
Further info

I have extracted the file from the textures.xbt file and it is definitely cyan.  This was from the 8.10 release downloaded via the official Kodi release ( not from the zip file from gitHub).


![australia_pg](https://user-images.githubusercontent.com/24578371/232174852-4aa53998-ecd8-40da-aac2-92c91f12d036.png)

**Comment by MikeSiLVO** [comment]
The conversion to Textures.xbt must be altering the file somehow. You can use the GitHub version of the skin until I have time to reach out and ask why the file is a different color.

**Comment by MikeSiLVO** [comment]
Gonna revert the files to before IMGBOT messed with them, please let me know if you see any other images that have the wrong colors 😃
