### ISSUE TITLE
Feature Request: Please support Xbian

### ISSUE THREAD

**Issue by Isayso** [MikeSiLVO/Aeon-Nox-SiLVO#178]
Please support xbian in system folder, xbian-config doesn't run on xbian (Nexus 20.1) with your skin activated.

I like your skin because of the bigger font and the easier workflow. Many people with eye problems (and we all get older) cannot use the default skin, the white on light blue font is hard to see on TVs and very small.

Thank you!

**Comment by MikeSiLVO** [comment]
I have no idea what this means 😕

**Comment by Isayso** [comment]
xbian.org
I dug a little bit deeper into this, the xbian config, you intergrated the libreelec config, is looking for some skin related data, which it doesn't find. The workaround is to switch back to Estuary, which is ok. 
It is probably more a xbian config related error than a skin feature itself. 
Looks like you need the config anyway only occasionally.   
 Thanks!
