### ISSUE TITLE
service.library.data.provider crashes Nexus

### ISSUE THREAD

**Issue by dekiesel** [MikeSiLVO/Aeon-Nox-SiLVO#183]
After installing the skin and clicking "Yes" when asked to install the service kodi crashes and can't start again.

After deleting `service.library.data.provider` from the `addons` folder kodi starts again.

The debug log is here: https://paste.kodi.tv/girofoqohi.kodi

**Comment by MikeSiLVO** [comment]
I do not have time to update that service so it has been removed as a requirement from the skin for Nexus and above.
Resolved with ade539bad865a3dded0715d836649870390440bb
