### ISSUE TITLE
Feature Request(s) - Hide videos watched as default & show video length

### ISSUE THREAD

**Issue by aindriu80** [MikeSiLVO/Aeon-Nox-SiLVO#184]
Hi,

Great skin, just two items that I can't seem to find in the settings - how do you show the length of a video when scrolling over videos in the video section? I had it before on other skins but it was one of the only features those skins had.  Is it possible to enable it on Videos?

The other feature is to hide videos watched as default - there is already an option to hide videos watched in Videos but you have to enable it every time you start up Kodi.  Is it possible to set it as a default?

Well done with the great skin!

**Comment by MikeSiLVO** [comment]
Not enough information so I will close this. Feel free to reopen if you can provide more details on the issue. Including a debug log and screenshots.
