### ISSUE TITLE
No Main Menu Background

### ISSUE THREAD

**Issue by robi782** [MikeSiLVO/Aeon-Nox-SiLVO#185]
Dear all,

thanks for reading.

I installed kodi on a Ubuntu system. After install from aeon nox there are no main menu backgrounds available.

Could someone help?

Thanks.
Robert

**Comment by MikeSiLVO** [comment]
There is zero information to go on so I will close this. Feel free to reopen if you can provide detailed information on the issue. Including a debug log and screenshots.
