### ISSUE TITLE
EPG - Overlapping Text

### ISSUE THREAD

**Issue by KarellenX** [MikeSiLVO/Aeon-Nox-SiLVO#186]
Hi @MikeSiLVO 

Wanting to report some overlapping text in the epg...
Regards

![epg](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/assets/44626605/93a2ed55-015c-4862-9763-214df10fba14)

**Comment by MikeSiLVO** [comment]
I cannot replicate this exact scenario. 
Can you please try the latest where I just removed the width tags for the label and let me know if that fixes it?

**Comment by KarellenX** [comment]
No luck.
Should have mentioned earlier I am on Omega and skin installed from repo.
The overlapping seems to occur when those guide segments are 5min or less duration (third arrow), or when only 5 minutes of the previous segment peeks out from the left margin (first 2 arrows)

When it is longer, the ellipses are displayed as shown on the last two lines.

**Comment by KarellenX** [comment]
Maybe those segments are too narrow to display the ellipses, so it falls back to displaying the full title?

**Comment by MikeSiLVO** [comment]
I think I can modify the demo client to show an item with that duration. I'll play around a bit and get back to you :)

**Comment by MikeSiLVO** [comment]
I think I got it. Please try the latest commit.

**Comment by KarellenX** [comment]
That fixed it. Thank you!!

Hope you are keeping well. I rarely see you on the forum anymore.

**Comment by MikeSiLVO** [comment]
You're welcome!
I try to read the forums when I can but finding the time and motivation for posting consistently eludes me... 😬

**Comment by MikeSiLVO** [comment]
Since this is fixed I will close the issue 😃
