### ISSUE TITLE
settings.xml get corrupt

### ISSUE THREAD

**Issue by mchawk777** [MikeSiLVO/Aeon-Nox-SiLVO#187]
Hallo and nice sunday everyone,

I've got the problem, that sometimes (I've noticed no pattern!) the settings.xml become corrupt.
Of course I have my backups an can repair this quit quickly - but it annoys me.

I have KODI sideloaded on 2 Amazon Firestick 4K (fist generation). Everything except this works fine.

My question is here:
When does the skin edit/alter/save the settings.xml?
Perhaps this info can narrowing down the problem.

Since Nexus KODI quit very fast, when I'm leaving the app.
Could storage operations still be carried out afterwards?

Thanks for any help or suggestion.

**Comment by MikeSiLVO** [comment]
The settings.xml file is only modified by Kodi when you change a skin setting. The skin can not interfere with that functionality. 
This is likely a Kodi issue. Please seek support on the Kodi forum.
https://forum.kodi.tv/

**Comment by mchawk777** [comment]
Thanks for the reply, Mike. 👍
Perhaps it's only an KODI on FireOS-Problem (Android).
I will ask it in the Kodi-Forum next time I'll be there. 😉
