### ISSUE TITLE
video player ratings

### ISSUE THREAD

**Issue by demex2008** [MikeSiLVO/Aeon-Nox-SiLVO#188]
![screenshot00000](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/assets/43509963/d475fcf7-c6a5-4c4b-a0d9-99ebd3121d12)
 
Can someone tell me how and where I do this

![screenshot00003](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/assets/43509963/e1ce00cf-f0ca-4d46-8a70-156d41ffd42d)
 
This is what it looks like in movie mode

mfg

**Comment by MikeSiLVO** [comment]
You are using a modified version of the skin. Please seek support from the person who modified it.
