### ISSUE TITLE
library-video-tvshow

### ISSUE THREAD

**Issue by demex2008** [MikeSiLVO/Aeon-Nox-SiLVO#190]
![screenshot00000](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/assets/43509963/5c184828-a09d-4fcb-a4ec-c295ae55a089)
![screenshot00001](https://github.com/MikeSiLVO/Aeon-Nox-SiLVO/assets/43509963/5929e0f6-42de-4ad4-8792-6c97bdc4f0b2)

Can you please tell me how I can set 99+ here again instead of resumable

**Comment by MikeSiLVO** [comment]
It looks like you are using a modified version of the skin. Please seek support from the person who modified it.
